import {TeacherRoster} from './teacher-modes';
import React,{useContext,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {api,useLoad,Obj,UserContext,Notice} from './shared';
import {DeviceList} from './management';
import {ClassroomContext} from './classroom-client';

export function TeacherWorkstations(){return <div className="admin-workstations teacher-workstations"><header className="classroom-title"><h1>Рабочие места</h1><Link className="button primary" to="/classroom/modes">Начать занятие</Link></header><div className="teacher-desktops"><section className="admin-workstation-card"><h2 className="section-title-bar">Подключённые рабочие места</h2><DeviceList/></section><TeacherRoster/></div></div>;}

export function Classroom(){
 const {data:connection}=useLoad('/classroom/connection');
 const u=useContext(UserContext),room=useContext(ClassroomContext),{data:stations,error,load}=useLoad('/classroom/stations',2200),{data:board}=useLoad('/learning/leaderboard',5000),{data:tickets}=useLoad('/tickets',5000);
 const [selected,setSelected]=useState<number[]>([]),[view,setView]=useState<string|null>(null),[err,setErr]=useState(''),[version,setVersion]=useState(''),[text,setText]=useState('');
 async function run(f:()=>Promise<any>){try{setErr('');await f();load();}catch(e:any){setErr(e.message);}}
 const pointerTime=useRef(0);
 const focused=view===null?undefined:(stations||[]).find((s:Obj)=>s.id===view),help=focused?room.links.find(l=>l.student_id===focused.user_id&&l.mode==='help'):undefined;
 function send(kind:string,payload:Obj){if(help)run(()=>api(`/classroom/links/${help.id}/signal`,'POST',{kind,payload}));}
 return <div className="classroom-page"><header className="classroom-title"><div><h1>{connection?.name||'Учебный класс'}</h1><p>Выберите ученика или несколько рабочих мест.</p></div><Link className="button primary" to="/classroom/modes">Начать обучение</Link></header><Notice>{error||err}</Notice>
 <details className="panel"><summary>Подключить ПК или телефон</summary><p>На ПК выберите этот сервер в окне запуска. На телефоне в той же Wi-Fi сети откройте один из адресов сервера:</p>{connection?.urls?.map((url:string)=><p key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></p>)}<p>На любом устройстве можно войти как администратор, преподаватель или ученик. Учётные записи и данные принадлежат выбранному учебному классу.</p></details>
 <div className="classroom-toolbar"><button onClick={()=>setSelected((board||[]).map((s:Obj)=>s.id))}>Выбрать всех</button><button onClick={()=>setSelected([])}>Снять выбор</button><button disabled={!selected.length} onClick={()=>run(async()=>{room.setSharing(true);await api('/classroom/links','POST',{students:selected,mode:'demo'});})}>Показать мой экран</button><button onClick={()=>room.setMicrophone(!room.microphone)}>{room.microphone?'Выключить микрофон':'Включить микрофон'}</button><button onClick={()=>run(async()=>{for(const l of room.links)await api('/classroom/links/'+l.id,'DELETE');room.setSharing(false);room.setMicrophone(false);})}>Завершить показ</button><select value={version} onChange={e=>setVersion(e.target.value)}><option value="">Билет для ручной отправки</option>{tickets?.filter((t:Obj)=>t.published&&!t.archived).map((t:Obj)=><option key={t.id} value={t.id} disabled={t.voice?.ready===false}>{t.data.title}{t.voice?.ready===false?` · звук ${t.voice.generated}/${t.voice.total}`:null}</option>)}</select><button disabled={!selected.length||!version} onClick={()=>run(()=>api('/assignments','POST',{version_id:Number(version),students:selected,training:true,start_mode:'self'}))}>Отправить задание</button></div>
 <div className="classroom-layout"><section><div className="station-grid">{stations?.map((s:Obj)=><article className={'station '+(selected.includes(s.user_id)?'selected':'')} key={s.id}><header><b>ПК {s.number}</b><span>{s.online?'В сети':'Не в сети'}</span></header><button className="screen-thumb" disabled={!s.user_id||s.role!=='student'||!s.online||!s.approved||s.blocked||!s.sharing} onClick={()=>setView(s.id)}>{s.frame?<img src={s.frame} alt={'Экран '+s.name}/>:<span>{s.approved?'Ученик ещё не включил показ экрана':'Ожидает допуска'}</span>}</button><label><input type="checkbox" disabled={!s.user_id||s.role!=='student'} checked={selected.includes(s.user_id)} onChange={()=>setSelected(selected.includes(s.user_id)?selected.filter(x=>x!==s.user_id):[...selected,s.user_id])}/>{s.name}</label>{u.role==='admin'&&<div>{!s.approved&&<button onClick={()=>run(()=>api('/classroom/stations/'+s.id,'PATCH',{approved:true,blocked:false}))}>Допустить ПК</button>}<button onClick={()=>run(()=>api('/classroom/stations/'+s.id,'PATCH',{blocked:!s.blocked}))}>{s.blocked?'Разрешить подключение':'Исключить ПК'}</button></div>}</article>)}</div>{!stations?.length&&<p className="panel">Подключённые рабочие места появятся здесь после указания номера ПК.</p>}</section>
 <aside className="classroom-roster"><h2>Студенты</h2>{board?.map((s:Obj)=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>setSelected(selected.includes(s.id)?selected.filter(x=>x!==s.id):[...selected,s.id])}/><span>{s.name}<small>ПК {s.station} · уровень {s.level}</small></span></label>)}</aside></div>
 <section className="panel"><h2>Результаты класса</h2><p>Уровень рассчитан по последним подтверждённым работам. Минивопросы учитываются отдельно.</p><table><thead><tr><th>Место</th><th>ФИО / ПК</th><th>Оценка</th><th>Среднее время</th><th>Замечания к тексту</th><th>Уровень</th><th>Рекомендация</th></tr></thead><tbody>{board?.map((s:Obj,i:number)=><tr key={s.id}><td>{s.score===null?'—':i+1}</td><td>{s.name} / {s.station}</td><td>{s.score===null?'Нет проверенных работ':s.score+'%'}</td><td>{s.seconds===null?'—':s.seconds+' с'}</td><td>{s.text_errors}</td><td>{s.level}</td><td>{s.recommendation}</td></tr>)}</tbody></table></section>
 {focused&&<div className="remote-overlay" data-no-capture><header><b>ПК {focused.number} · {focused.name}</b><button disabled={!focused.sharing||focused.role!=='student'} onClick={()=>run(()=>api('/classroom/links','POST',{students:[focused.user_id],mode:'help'}))}>Подключить помощь</button><button onClick={()=>{if(help)run(()=>api('/classroom/links/'+help.id,'DELETE'));setView(null);}}>Закрыть</button></header><p>{help?'Помощь включена: щёлкайте на экране. Ввод текста — в поле ниже.':'Просмотр экрана тренажёра'}</p>{focused.frame&&<img src={focused.frame} alt="Экран ученика" onMouseMove={e=>{if(!help||e.buttons||Date.now()-pointerTime.current<140)return;pointerTime.current=Date.now();const b=e.currentTarget.getBoundingClientRect();send('pointer',{x:(e.clientX-b.left)/b.width,y:(e.clientY-b.top)/b.height});}} onClick={e=>{const b=e.currentTarget.getBoundingClientRect();send('click',{x:(e.clientX-b.left)/b.width,y:(e.clientY-b.top)/b.height});}}/>}{help&&<div><input placeholder="Текст в выбранное поле ученика" value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>send('text',{text})}>Ввести</button><button onClick={()=>send('key',{key:'Enter'})}>Enter</button><button onClick={()=>send('scroll',{delta:400})}>Прокрутить вниз</button></div>}</div>}
 </div>;
}

export function ClassroomModes(){
 const {data:users}=useLoad('/users'),{data:groups}=useLoad('/groups'),{data:tickets}=useLoad('/tickets',5000),{data:services}=useLoad('/learning/services');
 const [mode,setMode]=useState('adaptive'),[students,setStudents]=useState<number[]>([]),[versions,setVersions]=useState<number[]>([]),[roles,setRoles]=useState<Obj>({}),[minutes,setMinutes]=useState(30),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const modes=[['sequential','Задания группе','Общий запуск выбранных билетов.'],['cooperative','112 → ДДС','Одна часть класса принимает звонки, другая получает их карточки.'],['adaptive','Каждый в своём темпе','Сложность и темп зависят от подтверждённых результатов.'],['sprint','Спринт карточек','Выполнить больше карточек за заданное время без переполнения очереди.']];
 return <div className="classroom-page"><h1>Как будем заниматься?</h1><div className="mode-grid">{modes.map(([id,title,description])=><button className={mode===id?'selected':''} key={id} onClick={()=>setMode(id)}><h2>{title}</h2><p>{description}</p></button>)}</div><div className="panel"><h2>1. Выберите студентов</h2><div className="actions">{groups?.map((g:Obj)=><button key={g.id} onClick={()=>setStudents((users||[]).filter((u:Obj)=>u.group_id===g.id&&u.role==='student'&&u.active).map((u:Obj)=>u.id))}>{g.name}</button>)}</div>{users?.filter((u:Obj)=>u.role==='student'&&u.active).map((u:Obj)=><div className="choice-line" key={u.id}><label><input type="checkbox" checked={students.includes(u.id)} onChange={()=>setStudents(students.includes(u.id)?students.filter(x=>x!==u.id):[...students,u.id])}/>{u.name}</label>{mode==='cooperative'&&students.includes(u.id)&&<select aria-label={'Роль '+u.name} value={roles[u.id]||'112'} onChange={e=>setRoles({...roles,[u.id]:e.target.value})}><option value="112">Оператор 112</option>{services?.filter((s:Obj)=>s.active).map((s:Obj)=><option key={s.name}>{s.name}</option>)}</select>}</div>)}</div><div className="panel"><h2>2. Выберите билеты</h2>{tickets?.filter((t:Obj)=>t.published&&!t.archived&&(mode!=='cooperative'||t.data.tasks.some((x:Obj)=>x.mode==='112'))).map((t:Obj)=><label className="choice-line" key={t.id}><input type="checkbox" disabled={t.voice?.ready===false} checked={versions.includes(t.id)} onChange={()=>setVersions(versions.includes(t.id)?versions.filter(x=>x!==t.id):[...versions,t.id])}/>{t.data.title} · {t.data.difficulty}{t.voice?.ready===false&&` · звук ${t.voice.generated}/${t.voice.total}`}</label>)}</div><div className="panel"><label>Длительность, минут <input type="number" min={1} max={240} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><p>Новички начинают со знакомства с интерфейсом. Занятие завершится по времени; преподаватель может остановить его раньше.</p><button className="primary" disabled={busy||!students.length||!versions.length} onClick={async()=>{setBusy(true);setMessage('');try{const l=await api('/lessons','POST',{title:modes.find(x=>x[0]===mode)?.[1]||'Занятие',students,versions,training:true,random_order:true,delivery_mode:mode,duration_minutes:minutes,roles:Object.fromEntries(students.map(s=>[s,roles[s]||'112']))});await api('/lessons/'+l.id+'/start','POST');setMessage('Занятие запущено. Студенты могут открыть его в разделе «Занятия».');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>Начать занятие</button><Notice>{message}</Notice><Link to="/lessons">Открыть текущие занятия</Link></div></div>;
}
