import {ArmJournal} from './arm-journal';
import React,{useContext,useState} from 'react';
import {Link} from 'react-router-dom';
import {UserContext,useLoad,Heading,Notice,Field,api,type Obj,statusNames} from './shared';
export function Library(){
 const u=useContext(UserContext),{data,error,load}=useLoad('/materials');const [show,setShow]=useState(false),[q,setQ]=useState('');
 return <div className="page"><Heading eyebrow="СПРАВОЧНАЯ БАЗА" title="ВИКИ">{u.role!=='student'&&<button className="primary" onClick={()=>setShow(!show)}>Добавить материал</button>}</Heading><section className="panel"><h2>Горячие клавиши тренажёра</h2><p><kbd>Ctrl + Enter</kbd> — принять входящий звонок 112 в открытой карточке.</p><p><kbd>Alt</kbd> — открыть управление обучением.</p><p><kbd>Tab</kbd> / <kbd>Shift + Tab</kbd> — следующее / предыдущее поле.</p></section><section className="panel"><h2>Работа с программой</h2><p>«Мои билеты» — назначенные билеты и первые шаги с подсказками. «Занятия с преподавателем» — запущенные для вас учебные сеансы. «Мой прогресс» показывает только ваши результаты.</p><p>Оператор 112 принимает вызов, уточняет сведения, заполняет карточку и оповещает службы. ДДС получает заполненную карточку и отмечает ход реагирования своей службы.</p><p>Сочетания клавиш оригинальных АРМ зависят от поставщика и версии. Например, в руководстве SI3000 Ctrl + Enter сохраняет изменения; в этом тренажёре назначение указано выше.</p></section><Notice>{error}</Notice>{show&&<MaterialForm done={()=>{setShow(false);load();}}/>}
 <div className="toolbar"><input aria-label="Поиск материалов" placeholder="Поиск по названию и тексту" value={q} onChange={e=>setQ(e.target.value)}/></div>{data?.filter((m:Obj)=>(m.title+m.body).toLowerCase().includes(q.toLowerCase())).map((m:Obj)=><details className="panel form-panel lesson-panel" key={m.id}><summary><b>{m.title}</b> · {m.group}</summary><div className="material-body">{m.body}</div></details>)}{!data?.length&&<p>Преподаватель пока не добавил материалы для вашей группы.</p>}</div>;
}
function MaterialForm({done}:{done:()=>void}){
 const {data:groups}=useLoad('/groups');const [title,setTitle]=useState(''),[body,setBody]=useState(''),[group,setGroup]=useState(''),[error,setError]=useState('');
 return <form className="panel form-panel" onSubmit={async e=>{e.preventDefault();try{await api('/materials','POST',{title,body,group_id:Number(group)});done();}catch(e:any){setError(e.message);}}}><Notice>{error}</Notice><Field label="Название"><input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Учебная группа"><select required value={group} onChange={e=>setGroup(e.target.value)}><option value="">Выберите группу</option>{groups?.map((g:Obj)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Текст методического материала"><textarea required minLength={10} rows={12} value={body} onChange={e=>setBody(e.target.value)}/></Field><label className="button">Загрузить текст (.txt / .md)<input type="file" hidden accept=".txt,.md" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>200000)throw Error('Максимум 200 КБ');setBody(await f.text());if(!title)setTitle(f.name);}catch(e:any){setError(e.message);}}}/></label><button className="primary">Сохранить для группы</button></form>;
}
export function Registry(){return <ArmJournal/>;}
