import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {api,useLoad,Notice,Obj,statusNames} from './shared';
import {Assessment} from './results';
import {ArmDialog} from './arm-ui';
const reviewed=(p:Obj)=>p.assessment?.reviews?.length&&!p.assessment?.pending&&!p.assessment?.ai_preliminary;
export function TeacherJournal(){
 const {data,error}=useLoad('/assignments',5000),[student,setStudent]=useState(''),[state,setState]=useState('completed'),[opened,setOpened]=useState<Obj|null>(null),[err,setErr]=useState('');
 const rows=(data||[]).flatMap((a:Obj)=>a.tasks.flatMap((task:Obj,index:number)=>{const attempts=a.attempts.filter((p:Obj)=>p.task_index===index);return (attempts.length?attempts:[{id:0,assignment:a.id,task_index:index,status:'assigned'}]).map((p:Obj)=>({...p,student:a.student,student_id:a.student_id,title:task.title||a.title}));})).filter((p:Obj)=>(!student||String(p.student_id)===student)&&(!state||(state==='review'?p.status==='completed'&&!reviewed(p):state==='active'?['active','ringing','paused'].includes(p.status):p.status===state)));
 return <div className="page"><h1>Проверка работ</h1><p>Откройте «Результат и оценка», изучите карточку и разговоры. Подтвердите текущую оценку или измените её: напротив критериев выберите «Зачесть» или «Не зачесть», добавьте комментарий и сохраните оценку.</p><Notice>{error||err}</Notice><div className="toolbar"><select aria-label="Ученик" value={student} onChange={e=>setStudent(e.target.value)}><option value="">Все ученики</option>{[...new Map((data||[]).map((a:Obj)=>[a.student_id,a.student])).entries()].map(([id,name]:any)=><option key={id} value={id}>{name}</option>)}</select><select aria-label="Состояние задания" value={state} onChange={e=>setState(e.target.value)}><option value="">Все задания</option><option value="assigned">Не начаты</option><option value="active">В работе</option><option value="completed">Завершены</option><option value="review">Нужна проверка</option></select></div><section className="panel table-panel"><table><thead><tr><th>Ученик</th><th>Задание</th><th>Состояние</th><th>Балл</th><th>Просмотр</th></tr></thead><tbody>{rows.map((p:Obj)=><tr key={p.id||'a'+p.assignment+':'+p.task_index}><td>{p.student}</td><td>{p.title}</td><td>{p.status==='assigned'?'Не начато':statusNames[p.status]||p.status}{p.assessment&&(reviewed(p)?' · проверено преподавателем':' · ожидает подтверждения')}</td><td>{p.assessment?.report_job&&p.assessment.report_job.status!=='done'?'Анализ ИИ…':p.assessment?.score??'Нет оценки'}</td><td>{p.id>0&&<><Link className="button" to={'/attempts/'+p.id}>Карточка</Link>{p.assessment&&<button onClick={async()=>{try{setOpened(await api('/attempts/'+p.id));}catch(e:any){setErr(e.message);}}}>Результат и оценка</button>}</>}</td></tr>)}</tbody></table>{!rows.length&&<p>Заданий по выбранным условиям нет.</p>}</section>{opened&&<ArmDialog className="assessment-modal" title="Результат и оценка" onClose={()=>setOpened(null)}><Assessment p={opened} onUpdate={setOpened}/></ArmDialog>}</div>;
}
