import {createPortal} from 'react-dom';
import {StudentHint} from './student-hint';
import React,{useEffect,useState,useContext,useRef} from 'react';
import {api,Obj,useLoad,UserContext,Notice} from './shared';

function keyName(e:KeyboardEvent){return (e.ctrlKey&&e.key!=='Control'?'Ctrl+':'')+(e.altKey&&e.key!=='Alt'?'Alt+':'')+e.key;}

export function IntroGate(){
 const u=useContext(UserContext),{data,load}=useLoad('/learning/profile'),[step,setStep]=useState(0),[message,setMessage]=useState('');
 if(u.role!=='student'||!data||data.intro_complete)return null;
 const pages=[['/assignments','Ваши задания','Здесь находятся назначенные вам билеты. Откройте первый, чтобы начать работу.'],['/lessons','Занятия с преподавателем','Здесь появится занятие, которое запустит преподаватель. Можно продолжить его после возвращения в программу.'],['/library','Учебные материалы','Здесь можно повторить правила работы. В карточке сочетание Ctrl + Enter принимает звонок, Alt открывает помощь.'],['/results','Ваши результаты','После выполнения карточек здесь можно посмотреть оценки и разобрать ошибки.']];
 const finish=async()=>{try{await api('/learning/intro','POST',{});load();}catch(e:any){setMessage(e.message);}};
 return <StudentHint key={step} target={'.student-learning-nav a[href="'+pages[step][0]+'"]'} onClose={finish}><small>ЗНАКОМСТВО · {step+1} / 4</small><h2>{pages[step][1]}</h2><p>{pages[step][2]}</p><button onClick={()=>step<3?setStep(step+1):finish()}>{step===3?'Начать работу':'Далее'}</button><Notice>{message}</Notice></StudentHint>;
}

export function MiniDrill({attemptId}:{attemptId:number}){
 const modal=useRef<HTMLDivElement>(null);
 const [q,setQ]=useState<Obj|null>(null),[answer,setAnswer]=useState(''),[result,setResult]=useState<Obj|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setQ(null);setResult(null);setAnswer('');api('/learning/drill/'+attemptId,'POST').then(r=>{if(active)setQ(r);}).catch(()=>{});return()=>{active=false;};},[attemptId]);
 useEffect(()=>{if(q?.kind!=='hotkey'||result)return;const handle=(e:KeyboardEvent)=>{if(e.key==='Tab')return;e.preventDefault();e.stopImmediatePropagation();setAnswer(keyName(e));};document.addEventListener('keydown',handle,true);return()=>document.removeEventListener('keydown',handle,true);},[q,result]);
 useEffect(()=>{if(!q)return;const el=modal.current;if(!el)return;const previous=document.activeElement as HTMLElement;const root=document.getElementById('root');root?.setAttribute('inert','');const items=()=>Array.from(el.querySelectorAll<HTMLElement>('input,button:not(:disabled),audio'));(items()[0]||el).focus();const key=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const all=items(),first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};el.addEventListener('keydown',key);return()=>{root?.removeAttribute('inert');el.removeEventListener('keydown',key);previous?.focus();};},[q?.id,!!result]);
 if(!q)return null;
 const content=<div ref={modal} tabIndex={-1} className="mini-drill mini-drill-modal" role="dialog" aria-modal="true" aria-label="Минизадание"><article><small>МИНУТКА ВНИМАНИЯ · НЕ ВЛИЯЕТ НА БАЛЛ ЗАДАНИЯ</small><h1>{q.prompt}</h1>{q.audio_id&&<audio controls autoPlay src={"/api/media/"+q.audio_id} aria-label="Прослушать минивопрос"/>}{result?<><p>{result.correct?'Верно!':'Правильный ответ: '+result.answer}</p><button onClick={()=>setQ(null)}>Перейти к карточке</button></>:<form onSubmit={async e=>{e.preventDefault();try{setResult(await api('/learning/drill-answer','POST',{id:q.id,answer}));}catch(e:any){setError(e.message);}}}>{q.kind==='choice'?q.options.map((v:string)=><label className="choice-line" key={v}><input type="radio" name="answer" checked={answer===v} onChange={()=>setAnswer(v)}/>{v}</label>):<input autoFocus aria-label="Ответ на минивопрос" readOnly={q.kind==='hotkey'} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={q.kind==='hotkey'?'Нажмите сочетание клавиш':'Введите ответ'}/>}<button className="primary" disabled={!answer}>Проверить</button><Notice>{error}</Notice></form>}</article></div>;
 return createPortal(content,document.body);
}

export function TrainingPhone(){
 const [last,setLast]=useState('Готов к работе'),[number,setNumber]=useState('');
 const press=(key:string)=>{setLast('Нажата кнопка: '+key);if(/^[0-9*#]$/.test(key))setNumber(n=>(n+key).slice(-20));};
 const button=(key:string,label=key)=><button type="button" key={key} title={key} onClick={()=>press(key)}>{label}</button>;
 return <section className="training-phone"><header>Учебный телефон · РТУ Т16Р</header><div className="rtu-body"><button className="rtu-handset" title="Трубка" onClick={()=>press('Трубка')}>☎</button><div className="rtu-main"><div className="rtu-brand">РТУ</div><div className="rtu-screen"><b>112 / ДДС</b><span>{number||'Учебная линия'}</span><small>{last}</small></div><div className="rtu-soft">{['Меню','Контакты','История','Назад'].map(k=>button(k))}</div><div className="rtu-navigation">{['←','↑','OK','↓','→'].map(k=>button(k))}</div><div className="rtu-digits">{'123456789*0#'.split('').map(k=>button(k))}</div><div className="rtu-actions">{['Удержание','Перевод','Гарнитура','Громкая связь','Откл. микрофон','Отбой'].map(k=>button(k))}</div></div><div className="rtu-extension">{[0,1].map(n=><div className="rtu-lines" key={n}>{Array.from({length:10},(_,i)=>button('Линия '+(n*10+i+1),'● '+(n*10+i+1)))}</div>)}</div></div><p role="status">{last}</p><small>Макет кнопок. Учебные разговоры — в панели связи ниже.</small></section>;
}

export function LearningEditor({questionsOnly=false}:{questionsOnly?:boolean}){
 const u=useContext(UserContext),{data:questions,load}=useLoad('/learning/questions'),{data:examples,load:reload}=useLoad('/learning/examples'),{data:services,load:reloadServices}=useLoad('/learning/services');
 const empty={prompt:'',kind:'text',answer:'',options:[],level:1,active:true};const [edit,setEdit]=useState<Obj>(empty),[error,setError]=useState(''),[service,setService]=useState('');
 async function run(fn:()=>Promise<any>){try{setError('');await fn();load();reload();reloadServices();}catch(e:any){setError(e.message);}}
 return <div className="classroom-page"><h1>{questionsOnly?'Минивопросы':'Учебные материалы и службы'}</h1><Notice>{error}</Notice><section className="panel"><h2>Минивопросы</h2><form className="form-panel" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/learning/questions'+(edit.id?'/'+edit.id:''),edit.id?'PUT':'POST',edit);setEdit(empty);});}}><label>Вопрос<input required value={edit.prompt} onChange={e=>setEdit({...edit,prompt:e.target.value})}/></label><label>Тип<select value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value})}><option value="text">Написать текст</option><option value="choice">Выбрать вариант</option><option value="hotkey">Нажать клавиши</option></select></label><label>Правильный ответ<input required value={edit.answer} onChange={e=>setEdit({...edit,answer:e.target.value})}/></label>{edit.kind==='choice'&&<label>Варианты, каждый с новой строки<textarea value={edit.options.join('\n')} onChange={e=>setEdit({...edit,options:e.target.value.split('\n')})}/></label>}<label>Минимальный уровень<input type="number" min={0} max={4} value={edit.level} onChange={e=>setEdit({...edit,level:Number(e.target.value)})}/></label><button className="primary">Сохранить вопрос</button></form>{questions?.map((q:Obj)=><div className="catalog-row" key={q.id}><span>{q.prompt} {q.active?'':'(скрыт)'}</span><button onClick={()=>setEdit(q)}>Изменить</button><button onClick={()=>run(()=>api('/learning/questions/'+q.id,'PUT',{...q,active:!q.active}))}>{q.active?'Удалить из обучения':'Вернуть'}</button></div>)}</section><section className="panel"><h2>Одобренные преподавателем ответы</h2><p>Используются для того же задания и критерия. Отозванный образец больше не передаётся модели.</p>{examples?.filter((e:Obj)=>e.active).map((e:Obj)=><div className="catalog-row" key={e.id}><div><b>{e.criterion}</b><p>{e.text}</p></div><button onClick={()=>run(()=>api('/learning/examples/'+e.id,'DELETE'))}>Отозвать образец</button></div>)}</section>{u.role==='admin'&&!questionsOnly&&<section className="panel"><h2>Службы</h2><form onSubmit={e=>{e.preventDefault();run(()=>api('/learning/services','POST',{name:service,active:true}));setService('');}}><input value={service} onChange={e=>setService(e.target.value)} minLength={2} required placeholder="Название новой службы"/><button>Добавить службу</button></form>{services?.map((s:Obj)=><div className="catalog-row" key={s.name}><span>{s.name}</span><button onClick={()=>run(()=>api('/learning/services','POST',{name:s.name,active:!s.active}))}>{s.active?'Убрать из выбора':'Вернуть'}</button></div>)}</section>}</div>;
}
